version: "3"
services:
  redis:
    image: redis:7.0.11
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis:/data
    container_name: redis
